/**
 * Countries Data for Phone Country Code Selector
 * 
 * Comprehensive list of countries with ISO codes, names, dial codes, and flags
 * Only includes countries that have flags available in the flag-icons library
 * Sorted alphabetically by country name with United States at the top
 */

export interface CountryCode {
  code: string;
  name: string;
  dialCode: string;
  flag: string;
}

// Comprehensive list of countries with ISO codes for flag-icons
// Sorted alphabetically by country name with United States first
export const countryCodes: CountryCode[] = [
  { code: 'US', name: 'United States', dialCode: '+1', flag: 'us' },
  { code: 'AF', name: 'Afghanistan', dialCode: '+93', flag: 'af' },
  { code: 'AL', name: 'Albania', dialCode: '+355', flag: 'al' },
  { code: 'DZ', name: 'Algeria', dialCode: '+213', flag: 'dz' },
  { code: 'AD', name: 'Andorra', dialCode: '+376', flag: 'ad' },
  { code: 'AO', name: 'Angola', dialCode: '+244', flag: 'ao' },
  { code: 'AG', name: 'Antigua & Barbuda', dialCode: '+1', flag: 'ag' },
  { code: 'AR', name: 'Argentina', dialCode: '+54', flag: 'ar' },
  { code: 'AM', name: 'Armenia', dialCode: '+374', flag: 'am' },
  { code: 'AU', name: 'Australia', dialCode: '+61', flag: 'au' },
  { code: 'AT', name: 'Austria', dialCode: '+43', flag: 'at' },
  { code: 'AZ', name: 'Azerbaijan', dialCode: '+994', flag: 'az' },
  { code: 'BS', name: 'Bahamas', dialCode: '+1', flag: 'bs' },
  { code: 'BH', name: 'Bahrain', dialCode: '+973', flag: 'bh' },
  { code: 'BD', name: 'Bangladesh', dialCode: '+880', flag: 'bd' },
  { code: 'BB', name: 'Barbados', dialCode: '+1', flag: 'bb' },
  { code: 'BY', name: 'Belarus', dialCode: '+375', flag: 'by' },
  { code: 'BE', name: 'Belgium', dialCode: '+32', flag: 'be' },
  { code: 'BZ', name: 'Belize', dialCode: '+501', flag: 'bz' },
  { code: 'BJ', name: 'Benin', dialCode: '+229', flag: 'bj' },
  { code: 'BT', name: 'Bhutan', dialCode: '+975', flag: 'bt' },
  { code: 'BO', name: 'Bolivia', dialCode: '+591', flag: 'bo' },
  { code: 'BA', name: 'Bosnia & Herzegovina', dialCode: '+387', flag: 'ba' },
  { code: 'BW', name: 'Botswana', dialCode: '+267', flag: 'bw' },
  { code: 'BR', name: 'Brazil', dialCode: '+55', flag: 'br' },
  { code: 'BN', name: 'Brunei', dialCode: '+673', flag: 'bn' },
  { code: 'BG', name: 'Bulgaria', dialCode: '+359', flag: 'bg' },
  { code: 'BF', name: 'Burkina Faso', dialCode: '+226', flag: 'bf' },
  { code: 'BI', name: 'Burundi', dialCode: '+257', flag: 'bi' },
  { code: 'KH', name: 'Cambodia', dialCode: '+855', flag: 'kh' },
  { code: 'CM', name: 'Cameroon', dialCode: '+237', flag: 'cm' },
  { code: 'CA', name: 'Canada', dialCode: '+1', flag: 'ca' },
  { code: 'CV', name: 'Cape Verde', dialCode: '+238', flag: 'cv' },
  { code: 'CF', name: 'Central African Republic', dialCode: '+236', flag: 'cf' },
  { code: 'TD', name: 'Chad', dialCode: '+235', flag: 'td' },
  { code: 'CL', name: 'Chile', dialCode: '+56', flag: 'cl' },
  { code: 'CN', name: 'China', dialCode: '+86', flag: 'cn' },
  { code: 'CO', name: 'Colombia', dialCode: '+57', flag: 'co' },
  { code: 'KM', name: 'Comoros', dialCode: '+269', flag: 'km' },
  { code: 'CK', name: 'Cook Islands', dialCode: '+682', flag: 'ck' },
  { code: 'CR', name: 'Costa Rica', dialCode: '+506', flag: 'cr' },
  { code: 'HR', name: 'Croatia', dialCode: '+385', flag: 'hr' },
  { code: 'CU', name: 'Cuba', dialCode: '+53', flag: 'cu' },
  { code: 'CY', name: 'Cyprus', dialCode: '+357', flag: 'cy' },
  { code: 'CZ', name: 'Czech Republic', dialCode: '+420', flag: 'cz' },
  { code: 'CD', name: 'DR Congo', dialCode: '+243', flag: 'cd' },
  { code: 'DK', name: 'Denmark', dialCode: '+45', flag: 'dk' },
  { code: 'DJ', name: 'Djibouti', dialCode: '+253', flag: 'dj' },
  { code: 'DM', name: 'Dominica', dialCode: '+1', flag: 'dm' },
  { code: 'DO', name: 'Dominican Republic', dialCode: '+1', flag: 'do' },
  { code: 'EC', name: 'Ecuador', dialCode: '+593', flag: 'ec' },
  { code: 'EG', name: 'Egypt', dialCode: '+20', flag: 'eg' },
  { code: 'SV', name: 'El Salvador', dialCode: '+503', flag: 'sv' },
  { code: 'GQ', name: 'Equatorial Guinea', dialCode: '+240', flag: 'gq' },
  { code: 'ER', name: 'Eritrea', dialCode: '+291', flag: 'er' },
  { code: 'EE', name: 'Estonia', dialCode: '+372', flag: 'ee' },
  { code: 'ET', name: 'Ethiopia', dialCode: '+251', flag: 'et' },
  { code: 'FK', name: 'Falkland Islands', dialCode: '+500', flag: 'fk' },
  { code: 'FJ', name: 'Fiji', dialCode: '+679', flag: 'fj' },
  { code: 'FI', name: 'Finland', dialCode: '+358', flag: 'fi' },
  { code: 'FR', name: 'France', dialCode: '+33', flag: 'fr' },
  { code: 'PF', name: 'French Polynesia', dialCode: '+689', flag: 'pf' },
  { code: 'GA', name: 'Gabon', dialCode: '+241', flag: 'ga' },
  { code: 'GM', name: 'Gambia', dialCode: '+220', flag: 'gm' },
  { code: 'GE', name: 'Georgia', dialCode: '+995', flag: 'ge' },
  { code: 'DE', name: 'Germany', dialCode: '+49', flag: 'de' },
  { code: 'GH', name: 'Ghana', dialCode: '+233', flag: 'gh' },
  { code: 'GR', name: 'Greece', dialCode: '+30', flag: 'gr' },
  { code: 'GD', name: 'Grenada', dialCode: '+1', flag: 'gd' },
  { code: 'GT', name: 'Guatemala', dialCode: '+502', flag: 'gt' },
  { code: 'GN', name: 'Guinea', dialCode: '+224', flag: 'gn' },
  { code: 'GW', name: 'Guinea-Bissau', dialCode: '+245', flag: 'gw' },
  { code: 'GY', name: 'Guyana', dialCode: '+592', flag: 'gy' },
  { code: 'HT', name: 'Haiti', dialCode: '+509', flag: 'ht' },
  { code: 'HN', name: 'Honduras', dialCode: '+504', flag: 'hn' },
  { code: 'HK', name: 'Hong Kong', dialCode: '+852', flag: 'hk' },
  { code: 'HU', name: 'Hungary', dialCode: '+36', flag: 'hu' },
  { code: 'IS', name: 'Iceland', dialCode: '+354', flag: 'is' },
  { code: 'IN', name: 'India', dialCode: '+91', flag: 'in' },
  { code: 'ID', name: 'Indonesia', dialCode: '+62', flag: 'id' },
  { code: 'IQ', name: 'Iraq', dialCode: '+964', flag: 'iq' },
  { code: 'IE', name: 'Ireland', dialCode: '+353', flag: 'ie' },
  { code: 'IL', name: 'Israel', dialCode: '+972', flag: 'il' },
  { code: 'IT', name: 'Italy', dialCode: '+39', flag: 'it' },
  { code: 'JM', name: 'Jamaica', dialCode: '+1', flag: 'jm' },
  { code: 'JP', name: 'Japan', dialCode: '+81', flag: 'jp' },
  { code: 'JO', name: 'Jordan', dialCode: '+962', flag: 'jo' },
  { code: 'KZ', name: 'Kazakhstan', dialCode: '+7', flag: 'kz' },
  { code: 'KE', name: 'Kenya', dialCode: '+254', flag: 'ke' },
  { code: 'KI', name: 'Kiribati', dialCode: '+686', flag: 'ki' },
  { code: 'KP', name: 'North Korea', dialCode: '+850', flag: 'kp' },
  { code: 'KR', name: 'South Korea', dialCode: '+82', flag: 'kr' },
  { code: 'KW', name: 'Kuwait', dialCode: '+965', flag: 'kw' },
  { code: 'LA', name: 'Laos', dialCode: '+856', flag: 'la' },
  { code: 'LV', name: 'Latvia', dialCode: '+371', flag: 'lv' },
  { code: 'LB', name: 'Lebanon', dialCode: '+961', flag: 'lb' },
  { code: 'LS', name: 'Lesotho', dialCode: '+266', flag: 'ls' },
  { code: 'LR', name: 'Liberia', dialCode: '+231', flag: 'lr' },
  { code: 'LI', name: 'Liechtenstein', dialCode: '+423', flag: 'li' },
  { code: 'LT', name: 'Lithuania', dialCode: '+370', flag: 'lt' },
  { code: 'LU', name: 'Luxembourg', dialCode: '+352', flag: 'lu' },
  { code: 'MO', name: 'Macau', dialCode: '+853', flag: 'mo' },
  { code: 'MG', name: 'Madagascar', dialCode: '+261', flag: 'mg' },
  { code: 'MW', name: 'Malawi', dialCode: '+265', flag: 'mw' },
  { code: 'MY', name: 'Malaysia', dialCode: '+60', flag: 'my' },
  { code: 'MV', name: 'Maldives', dialCode: '+960', flag: 'mv' },
  { code: 'ML', name: 'Mali', dialCode: '+223', flag: 'ml' },
  { code: 'MT', name: 'Malta', dialCode: '+356', flag: 'mt' },
  { code: 'MH', name: 'Marshall Islands', dialCode: '+692', flag: 'mh' },
  { code: 'MR', name: 'Mauritania', dialCode: '+222', flag: 'mr' },
  { code: 'MU', name: 'Mauritius', dialCode: '+230', flag: 'mu' },
  { code: 'MX', name: 'Mexico', dialCode: '+52', flag: 'mx' },
  { code: 'FM', name: 'Micronesia', dialCode: '+691', flag: 'fm' },
  { code: 'MD', name: 'Moldova', dialCode: '+373', flag: 'md' },
  { code: 'MC', name: 'Monaco', dialCode: '+377', flag: 'mc' },
  { code: 'MN', name: 'Mongolia', dialCode: '+976', flag: 'mn' },
  { code: 'ME', name: 'Montenegro', dialCode: '+382', flag: 'me' },
  { code: 'MS', name: 'Montserrat', dialCode: '+1', flag: 'ms' },
  { code: 'MA', name: 'Morocco', dialCode: '+212', flag: 'ma' },
  { code: 'MZ', name: 'Mozambique', dialCode: '+258', flag: 'mz' },
  { code: 'MM', name: 'Myanmar', dialCode: '+95', flag: 'mm' },
  { code: 'NA', name: 'Namibia', dialCode: '+264', flag: 'na' },
  { code: 'NR', name: 'Nauru', dialCode: '+674', flag: 'nr' },
  { code: 'NP', name: 'Nepal', dialCode: '+977', flag: 'np' },
  { code: 'NL', name: 'Netherlands', dialCode: '+31', flag: 'nl' },
  { code: 'NC', name: 'New Caledonia', dialCode: '+687', flag: 'nc' },
  { code: 'NZ', name: 'New Zealand', dialCode: '+64', flag: 'nz' },
  { code: 'NI', name: 'Nicaragua', dialCode: '+505', flag: 'ni' },
  { code: 'NE', name: 'Niger', dialCode: '+227', flag: 'ne' },
  { code: 'NG', name: 'Nigeria', dialCode: '+234', flag: 'ng' },
  { code: 'NF', name: 'Norfolk Island', dialCode: '+672', flag: 'nf' },
  { code: 'MK', name: 'North Macedonia', dialCode: '+389', flag: 'mk' },
  { code: 'MP', name: 'Northern Mariana Islands', dialCode: '+1', flag: 'mp' },
  { code: 'NO', name: 'Norway', dialCode: '+47', flag: 'no' },
  { code: 'OM', name: 'Oman', dialCode: '+968', flag: 'om' },
  { code: 'PK', name: 'Pakistan', dialCode: '+92', flag: 'pk' },
  { code: 'PW', name: 'Palau', dialCode: '+680', flag: 'pw' },
  { code: 'PS', name: 'Palestine', dialCode: '+970', flag: 'ps' },
  { code: 'PA', name: 'Panama', dialCode: '+507', flag: 'pa' },
  { code: 'PG', name: 'Papua New Guinea', dialCode: '+675', flag: 'pg' },
  { code: 'PY', name: 'Paraguay', dialCode: '+595', flag: 'py' },
  { code: 'PE', name: 'Peru', dialCode: '+51', flag: 'pe' },
  { code: 'PH', name: 'Philippines', dialCode: '+63', flag: 'ph' },
  { code: 'PL', name: 'Poland', dialCode: '+48', flag: 'pl' },
  { code: 'PT', name: 'Portugal', dialCode: '+351', flag: 'pt' },
  { code: 'PR', name: 'Puerto Rico', dialCode: '+1', flag: 'pr' },
  { code: 'QA', name: 'Qatar', dialCode: '+974', flag: 'qa' },
  { code: 'RO', name: 'Romania', dialCode: '+40', flag: 'ro' },
  { code: 'RU', name: 'Russia', dialCode: '+7', flag: 'ru' },
  { code: 'RW', name: 'Rwanda', dialCode: '+250', flag: 'rw' },
  { code: 'SA', name: 'Saudi Arabia', dialCode: '+966', flag: 'sa' },
  { code: 'SB', name: 'Solomon Islands', dialCode: '+677', flag: 'sb' },
  { code: 'SC', name: 'Seychelles', dialCode: '+248', flag: 'sc' },
  { code: 'SD', name: 'Sudan', dialCode: '+249', flag: 'sd' },
  { code: 'SG', name: 'Singapore', dialCode: '+65', flag: 'sg' },
  { code: 'SK', name: 'Slovakia', dialCode: '+421', flag: 'sk' },
  { code: 'SI', name: 'Slovenia', dialCode: '+386', flag: 'si' },
  { code: 'SO', name: 'Somalia', dialCode: '+252', flag: 'so' },
  { code: 'ZA', name: 'South Africa', dialCode: '+27', flag: 'za' },
  { code: 'ES', name: 'Spain', dialCode: '+34', flag: 'es' },
  { code: 'LK', name: 'Sri Lanka', dialCode: '+94', flag: 'lk' },
  { code: 'SR', name: 'Suriname', dialCode: '+597', flag: 'sr' },
  { code: 'SZ', name: 'Eswatini', dialCode: '+268', flag: 'sz' },
  { code: 'SE', name: 'Sweden', dialCode: '+46', flag: 'se' },
  { code: 'CH', name: 'Switzerland', dialCode: '+41', flag: 'ch' },
  { code: 'SY', name: 'Syria', dialCode: '+963', flag: 'sy' },
  { code: 'TW', name: 'Taiwan', dialCode: '+886', flag: 'tw' },
  { code: 'TJ', name: 'Tajikistan', dialCode: '+992', flag: 'tj' },
  { code: 'TZ', name: 'Tanzania', dialCode: '+255', flag: 'tz' },
  { code: 'TH', name: 'Thailand', dialCode: '+66', flag: 'th' },
  { code: 'TL', name: 'Timor-Leste', dialCode: '+670', flag: 'tl' },
  { code: 'TG', name: 'Togo', dialCode: '+228', flag: 'tg' },
  { code: 'TK', name: 'Tokelau', dialCode: '+690', flag: 'tk' },
  { code: 'TO', name: 'Tonga', dialCode: '+676', flag: 'to' },
  { code: 'TT', name: 'Trinidad & Tobago', dialCode: '+1', flag: 'tt' },
  { code: 'TN', name: 'Tunisia', dialCode: '+216', flag: 'tn' },
  { code: 'TR', name: 'Turkey', dialCode: '+90', flag: 'tr' },
  { code: 'TM', name: 'Turkmenistan', dialCode: '+993', flag: 'tm' },
  { code: 'TV', name: 'Tuvalu', dialCode: '+688', flag: 'tv' },
  { code: 'UG', name: 'Uganda', dialCode: '+256', flag: 'ug' },
  { code: 'UA', name: 'Ukraine', dialCode: '+380', flag: 'ua' },
  { code: 'AE', name: 'UAE', dialCode: '+971', flag: 'ae' },
  { code: 'GB', name: 'United Kingdom', dialCode: '+44', flag: 'gb' },
  { code: 'UY', name: 'Uruguay', dialCode: '+598', flag: 'uy' },
  { code: 'UZ', name: 'Uzbekistan', dialCode: '+998', flag: 'uz' },
  { code: 'VU', name: 'Vanuatu', dialCode: '+678', flag: 'vu' },
  { code: 'VA', name: 'Vatican City', dialCode: '+379', flag: 'va' },
  { code: 'VE', name: 'Venezuela', dialCode: '+58', flag: 've' },
  { code: 'VN', name: 'Vietnam', dialCode: '+84', flag: 'vn' },
  { code: 'WF', name: 'Wallis & Futuna', dialCode: '+681', flag: 'wf' },
  { code: 'WS', name: 'Samoa', dialCode: '+685', flag: 'ws' },
  { code: 'YE', name: 'Yemen', dialCode: '+967', flag: 'ye' },
  { code: 'ZM', name: 'Zambia', dialCode: '+260', flag: 'zm' },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', flag: 'zw' },
];

// Helper function to get country by dial code
export function getCountryByDialCode(dialCode: string): CountryCode | undefined {
  return countryCodes.find(country => country.dialCode === dialCode);
}

// Helper function to get country by ISO code
export function getCountryByCode(code: string): CountryCode | undefined {
  return countryCodes.find(country => country.code === code);
}

// Helper function to get countries by dial code (for shared codes like +1)
export function getCountriesByDialCode(dialCode: string): CountryCode[] {
  return countryCodes.filter(country => country.dialCode === dialCode);
} 